### ISSUE TITLE
Issue here on WSL2 (ubuntu 20.04), swift 5.6 and vscode-swif x0.4.1.

### ISSUE THREAD

**Issue by adam-fowler** [swift-server/vscode-swift#224]
Similar issue here on WSL2 (ubuntu 20.04), swift 5.6 and vscode-swif x0.4.1.

I wasn't prompted to install CodeLLDB. When I wanted to manually install it it was already installd.
However, the code-competion, jump to definition etc. doesn't work.

I noticed that the "Runtime Status" of the extention has an uncaught error "missing expected parameter: params". Does that help?

![grafik](https://user-images.githubusercontent.com/4357767/161448514-a9b14835-e93a-461d-9ea6-5598da118130.png)

I can see that the extention is working to some extend.
After building my project, the extention finds and can build + excecute tests them.
Although during debugging it doesn't show the state of variables. It only lists the register contents.
Maybe that functionality doesn't exist yet but I'd expect the variable `t` and `s`to be listed under local variables (and hovering on them should probably show their value).

![grafik](https://user-images.githubusercontent.com/4357767/161448227-fa2b4953-d203-4b2e-85b7-be5242655979.png)

_Originally posted by @jonha892 in https://github.com/swift-server/vscode-swift/issues/195#issuecomment-1086949504_

**Comment by adam-fowler** [comment]
@jonha892 @ARKAD97 I'm seeing this now. It seems to be a general linux issue. I have another release coming out hopefully  by the end of the day which should resolve this issue.

**Comment by adam-fowler** [comment]
@jonha892 @ARKAD97 can you guys test v0.4.3. This should be an improvement. The problem you are seeing is related to the LSP server failing to shut down on Linux. On startup it was possible that the LSP server would restart which caused it to crash. I have now sorted it such that it won't restart and thus not crash.

The shutdown failure will need to be resolved by a change to the SourceKit-lsp server which comes packaged with your swift install. So that isn't going to get fixed before we see a patch release of Swift.

If you have a workspace with multiple swift projects, this will not work on Linux until we see the swift patch release as moving between projects requires a restart of the LSP server.

**Comment by ARKAD97** [comment]
Thanks, with v0.4.3 code completion, jump to definition, etc. work now.
I've just tried to debug swift code with using breakpoints, looking at variables and so on - everything works.

For me issue is solved, many thanks.

**Comment by adam-fowler** [comment]
Can we keep this one open @0xTim . I'd like to hear from @jonha892 whether it works on WSL2

**Comment by rahmedd** [comment]
I'm still having this issue. I'm on WSL2, Ubuntu 20.04, Swift 5.6.1, and 0.5 version of the plugin. I have the lldb: Library set correctly, Please let me know if I can provide any other information.

**Comment by adam-fowler** [comment]
> I'm still having this issue. I'm on WSL2, Ubuntu 20.04, Swift 5.6.1, and 0.5 version of the plugin. I have the lldb: Library set correctly, Please let me know if I can provide any other information.

Can you copy and paste the contents of the Swift Output View here when it fails. That would be helpful.

**Comment by rahmedd** [comment]
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/lldb/__init__.py", line 11409, in <module>
    class SBTraceOptions(object):
  File "/usr/lib/python3/dist-packages/lldb/__init__.py", line 11468, in SBTraceOptions
    __swig_destroy__ = _lldb.delete_SBTraceOptions
AttributeError: module '_lldb' has no attribute 'delete_SBTraceOptions'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'lldb' is not defined
[2022-05-08T06:04:52.873Z ERROR codelldb::debug_session] Initialize Python interpreter: Error:  Fail
    Error Message:
    error: module importing failed: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/r/.vscode-server/extensions/vadimcn.vscode-lldb-1.7.0/adapter/debugger.py", line 2, in <module>
        import lldb
      File "/usr/lib/python3/dist-packages/lldb/__init__.py", line 11409, in <module>
        class SBTraceOptions(object):
      File "/usr/lib/python3/dist-packages/lldb/__init__.py", line 11468, in SBTraceOptions
        __swig_destroy__ = _lldb.delete_SBTraceOptions
    AttributeError: module '_lldb' has no attribute 'delete_SBTraceOptions'
    
```

**Comment by adam-fowler** [comment]
@rahmedd Can you run your application in `lldb` outside of VSCode?
Also what is the output from `lldb --version`?

**Comment by rahmedd** [comment]
How do I run the application from LLDB directly? The application runs properly, I'm able to set breakpoints but I'm not able to read variables. ![image](https://user-images.githubusercontent.com/57196639/167310037-90402c7d-6d56-4a9b-abd9-181a4a2b876d.png)

lldb --version output:
```
lldb version 13.0.0 (https://github.com/apple/llvm-project.git revision f765bf5b71fd3637a6f6d1d3e6ab95ca91892a0c)
Swift version 5.6.1 (swift-5.6.1-RELEASE)
```

**Comment by adam-fowler** [comment]
From your screenshot, you seem to have variables visible in your local variables view. What is the exact issue you are seeing here? The problem with this GH Issue is it is quite general. Is code completion, jump to definition working? Are your problems with the debugger?

**Comment by adam-fowler** [comment]
@rahmedd This seems to be a general issue with Ubuntu 20.04 and Swift 5.6 and later. I have added a bug in the swift llvm-project repo https://github.com/apple/llvm-project/issues/4770

**Comment by rahmedd** [comment]
The variables are visible but they're all deeply nested in something else. Not sure if this is expected behavior. I'm going to hold off on using server-side swift for now. Let me know if I can provide any info to help other users. Thanks for your help!
